# Generated by Django 5.1.3 on 2024-11-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('short_team_goals', models.TextField()),
                ('long_team_goals', models.TextField()),
                ('current_media', models.TextField()),
                ('desired_media', models.TextField()),
                ('marketing_share', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('strengths', models.TextField()),
                ('weaknesses', models.TextField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('audience_demographic', models.TextField()),
                ('geographic_focus', models.CharField(choices=[('iran', 'Iran'), ('international', 'International')], max_length=50)),
            ],
        ),
    ]
