# Generated by Django 5.1.3 on 2024-12-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefmarket', '0002_marketingbrief_audience_environments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingbrief',
            old_name='dollar',
            new_name='budget_dollar',
        ),
        migrations.RenameField(
            model_name='marketingbrief',
            old_name='euro',
            new_name='budget_euro',
        ),
        migrations.RenameField(
            model_name='marketingbrief',
            old_name='toman',
            new_name='budget_toman',
        ),
        migrations.RemoveField(
            model_name='marketingbrief',
            name='budget',
        ),
        migrations.AddField(
            model_name='marketingbrief',
            name='brand_book',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='marketingbrief',
            name='company_slogan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='marketingbrief',
            name='estimated_revenue',
            field=models.CharField(choices=[('above_15m', 'Above 15m'), ('8_to_15m', '8 to 15m'), ('4_to_8m', '4 to 8m'), ('under_4m', 'Under 4m')], default='under_4m', max_length=50),
        ),
        migrations.AddField(
            model_name='marketingbrief',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=50),
        ),
        migrations.AddField(
            model_name='marketingbrief',
            name='importance',
            field=models.CharField(choices=[('quality', 'Quality'), ('price', 'Price'), ('brand_name', 'Brand Name'), ('services', 'Services'), ('availability', 'Availability'), ('other', 'Other')], default='quality', max_length=50),
        ),
        migrations.AddField(
            model_name='marketingbrief',
            name='main_audience',
            field=models.CharField(choices=[('children', 'Children'), ('youth', 'Youth'), ('adults', 'Adults'), ('elderly', 'Elderly')], default='children', max_length=50),
        ),
        migrations.AddField(
            model_name='marketingbrief',
            name='target_audience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='marketingbrief',
            name='target_dollar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='دلار'),
        ),
        migrations.AddField(
            model_name='marketingbrief',
            name='target_euro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='یورو'),
        ),
        migrations.AddField(
            model_name='marketingbrief',
            name='target_toman',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تومان'),
        ),
    ]
